//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabuada.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tabuada.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuada.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabua por um número maior que 1000 pode travar seu telefone... Aguarde enquanto o telefone processa a conta.
        /// </summary>
        internal static string AvisoTabuaNumMaior1000 {
            get {
                return ResourceManager.GetString("AvisoTabuaNumMaior1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string BotaoConfiguracoes {
            get {
                return ResourceManager.GetString("BotaoConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zerar contador.
        /// </summary>
        internal static string bt_zerarCont {
            get {
                return ResourceManager.GetString("bt_zerarCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classificar.
        /// </summary>
        internal static string Classificar {
            get {
                return ResourceManager.GetString("Classificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classifique esse aplicativo.
        /// </summary>
        internal static string ClassificarApp {
            get {
                return ResourceManager.GetString("ClassificarApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número é divisível por 10 quando ele termina em 0.
        /// </summary>
        internal static string ComoTabuarPor10 {
            get {
                return ResourceManager.GetString("ComoTabuarPor10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número é divisível por 2 quando ele é PAR.
        /// </summary>
        internal static string ComoTabuarPor2 {
            get {
                return ResourceManager.GetString("ComoTabuarPor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to um número é divisível por 3 quando a soma de todos seus algarismos for um múltiplo de 3.
        ///
        ///Por exemplo: 3258 é divisível por 3.
        ///
        ///3 + 2 + 5 + 8 = 18. 18 é multiplo de 3, então 3258 também é.
        /// </summary>
        internal static string ComoTabuarPor3 {
            get {
                return ResourceManager.GetString("ComoTabuarPor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número será divisível por 4 quando seus dois últimos algarismos for um múltiplo de 4.
        ///
        ///Por exemplo: 25412 este número é divisível por 4 pois seus dois últimos algarismos, 12, formam um número múltiplo de 4(4 x 3 = 12)
        ///
        ///Dica: Para ver se o número formado pelos dois algarismos é múltiplo de 4, podemos fazer uma conta rápida. Primeiro, o número deve ser par, e sua metade também deve ser par
        ///
        ///Por Exemplo: 23564 é divisível por 4, pegamos o 64 e vemos que é par, sua metade 32 também é par, então 23564 é [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComoTabuarPor4 {
            get {
                return ResourceManager.GetString("ComoTabuarPor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número é divisível por 5 quando ele termina em 0 ou 5.
        /// </summary>
        internal static string ComoTabuarPor5 {
            get {
                return ResourceManager.GetString("ComoTabuarPor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número é divisível por 6 quando ele for divisível por 2 e 3 ao mesmo tempo.
        /// </summary>
        internal static string ComoTabuarPor6 {
            get {
                return ResourceManager.GetString("ComoTabuarPor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número é divisível por 8 quando seus últimos três algarismos formarem um número múltiplo de 8.
        /// </summary>
        internal static string ComoTabuarPor8 {
            get {
                return ResourceManager.GetString("ComoTabuarPor8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um número é divisível por 9 quando a soma de seus algarismos resultar em um número múltiplo de 9.
        /// </summary>
        internal static string ComoTabuarPor9 {
            get {
                return ResourceManager.GetString("ComoTabuarPor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dividir.
        /// </summary>
        internal static string ComoTabuarTitle {
            get {
                return ResourceManager.GetString("ComoTabuarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aprender.
        /// </summary>
        internal static string Curiosidades {
            get {
                return ResourceManager.GetString("Curiosidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvido por Douglas Nunes de Mattos.
        /// </summary>
        internal static string DesenvolvidoPor {
            get {
                return ResourceManager.GetString("DesenvolvidoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dividido por.
        /// </summary>
        internal static string DividindoSpeak {
            get {
                return ResourceManager.GetString("DividindoSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É igual a .
        /// </summary>
        internal static string EigualSpeak {
            get {
                return ResourceManager.GetString("EigualSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite até onde tabua.
        /// </summary>
        internal static string ErroFaltandoNumAteOndeTabua {
            get {
                return ResourceManager.GetString("ErroFaltandoNumAteOndeTabua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número para tabua.
        /// </summary>
        internal static string ErroFaltandoNumTabua {
            get {
                return ResourceManager.GetString("ErroFaltandoNumTabua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aprenda a dividir por.
        /// </summary>
        internal static string HomeAprenderTabua {
            get {
                return ResourceManager.GetString("HomeAprenderTabua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira os números.
        /// </summary>
        internal static string HomeInserirNum {
            get {
                return ResourceManager.GetString("HomeInserirNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir resultados até quando?.
        /// </summary>
        internal static string HomeNumAteOnde {
            get {
                return ResourceManager.GetString("HomeNumAteOnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuada de que número?.
        /// </summary>
        internal static string HomeNumTabua {
            get {
                return ResourceManager.GetString("HomeNumTabua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ler.
        /// </summary>
        internal static string Ler {
            get {
                return ResourceManager.GetString("Ler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuando.
        /// </summary>
        internal static string LiveTileTabuando {
            get {
                return ResourceManager.GetString("LiveTileTabuando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vezes.
        /// </summary>
        internal static string LiveTileVezesTabuando {
            get {
                return ResourceManager.GetString("LiveTileVezesTabuando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo deu errado :(.
        /// </summary>
        internal static string MgsAlgoDeuErrado {
            get {
                return ResourceManager.GetString("MgsAlgoDeuErrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiplicado por.
        /// </summary>
        internal static string MultiplicandoSpeak {
            get {
                return ResourceManager.GetString("MultiplicandoSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configurações.
        /// </summary>
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dividindo.
        /// </summary>
        internal static string PanoramaDividindoTitle {
            get {
                return ResourceManager.GetString("PanoramaDividindoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiplicando.
        /// </summary>
        internal static string PanoramaMultiplicandoTitle {
            get {
                return ResourceManager.GetString("PanoramaMultiplicandoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resultados.
        /// </summary>
        internal static string PanoramaResultadosTitle {
            get {
                return ResourceManager.GetString("PanoramaResultadosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to somando.
        /// </summary>
        internal static string PanoramaSomandoTitle {
            get {
                return ResourceManager.GetString("PanoramaSomandoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtraindo.
        /// </summary>
        internal static string PanoramaSubtraindoTitle {
            get {
                return ResourceManager.GetString("PanoramaSubtraindoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oi, estou me esforçando para fazer o melhor aplicativo para tabuada para o Windows Phone, você poderia me ajudar fazendo um comentário para mim?.
        /// </summary>
        internal static string PedicaoDeReview {
            get {
                return ResourceManager.GetString("PedicaoDeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to por.
        /// </summary>
        internal static string PorComoTabuarPage {
            get {
                return ResourceManager.GetString("PorComoTabuarPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contas feitas.
        /// </summary>
        internal static string SettingsContasFeitas {
            get {
                return ResourceManager.GetString("SettingsContasFeitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sobre.
        /// </summary>
        internal static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mais.
        /// </summary>
        internal static string SomandoSpeak {
            get {
                return ResourceManager.GetString("SomandoSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menos.
        /// </summary>
        internal static string SubtraindoSpeak {
            get {
                return ResourceManager.GetString("SubtraindoSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calcular.
        /// </summary>
        internal static string Tabua {
            get {
                return ResourceManager.GetString("Tabua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poderia me ajudar?.
        /// </summary>
        internal static string TitlePedicaodeReview {
            get {
                return ResourceManager.GetString("TitlePedicaodeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contar quantidade de contas feitas?.
        /// </summary>
        internal static string UpdateContLiveTiles {
            get {
                return ResourceManager.GetString("UpdateContLiveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir atualizações no bloco do aplicativo?.
        /// </summary>
        internal static string UpdateLiveTiles {
            get {
                return ResourceManager.GetString("UpdateLiveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão.
        /// </summary>
        internal static string Versao {
            get {
                return ResourceManager.GetString("Versao", resourceCulture);
            }
        }
    }
}
